# Generated by Django 5.2.17 on 2026-09-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchmodel",
            name="column_mapping",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
