# Generated by Django 5.2.17 on 2026-09-25 15:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_transactions(apps, schema_editor):
    """Project the batches analysed before the read model existed."""
    from ledger.domain.entities import Batch

    batch_model = apps.get_model("ledger", "BatchModel")
    transaction_model = apps.get_model("ledger", "TransactionModel")
    for stored in batch_model.objects.exclude(analysis_report=None).iterator():
        batch = Batch.model_validate(
            {
                "id": stored.id,
                "reference": stored.reference,
                "status": stored.status,
                "created_by": stored.created_by,
                "created_at": stored.created_at,
                "rows": stored.source_rows,
                "column_mapping": stored.column_mapping,
                "analysis": stored.analysis_report,
                "decided_by": stored.decided_by,
                "decided_at": stored.decided_at,
                "rejection_reason": stored.rejection_reason,
            }
        )
        transaction_model.objects.bulk_create(
            [
                transaction_model(batch_id=stored.id, **t.model_dump(exclude={"batch_id"}))
                for t in batch.valid_transactions()
            ],
            batch_size=1000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_batch_column_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("external_id", models.CharField(max_length=255)),
                ("account", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("value_date", models.DateField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("INFLOW", "INFLOW"), ("OUTFLOW", "OUTFLOW")],
                        max_length=8,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ledger.batchmodel",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_transaction",
                "ordering": ["value_date", "batch_id", "row_number"],
                "indexes": [
                    models.Index(fields=["value_date"], name="ledger_tx_date"),
                    models.Index(
                        fields=["account", "value_date"], name="ledger_tx_account_date"
                    ),
                    models.Index(
                        fields=["currency", "value_date"],
                        name="ledger_tx_currency_date",
                    ),
                    models.Index(fields=["external_id"], name="ledger_tx_external_id"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"), name="ledger_tx_unique_row"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="ledger_tx_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("direction__in", ["INFLOW", "OUTFLOW"])),
                        name="ledger_tx_direction_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_transactions, migrations.RunPython.noop),
    ]
